### ISSUE TITLE
"cp" command not working 

### ISSUE THREAD

**Issue by dacobi** [irmen/cx16shell#11] opened 2024-02-23 15:18 UTC
I'm having a problem with the "cp" command.

Even though the files are absolutely there the syntax: 
cp oldfile newfile
Always gives me an error: 
31, SYNTAX ERROR, 00, 00

I've tried with the version that came on the SD card and also I've compiled v1.2.

My ROM version is R47 pre-release.

**Comment by adiee5** [comment] 2024-02-23 15:21
check if it's reproducible in R46? we don't test the shell on non-release ROMs

**Comment by dacobi** [comment] 2024-02-23 15:25
I can't test with R46 right now, since I don't have an EPROM programmer yet and I don't have the nerves to flash without hardware backup :)
But I should be able to get one next week and then I can test.

**Comment by adiee5** [comment] 2024-02-23 15:27
umm, why did you flash unfinished rom into your hardware in the first place?

**Comment by adiee5** [comment] 2024-02-23 15:37
> I didn't, my board came with that ROM version

really? weird

**Comment by dacobi** [comment] 2024-02-23 15:41
My board arrived with these firmware versions:

https://cx16forum.com/forum/viewtopic.php?p=31742#p31742

**Comment by adiee5** [comment] 2024-02-23 15:43
Did you happen to try copying between folders? Because now when i look at kernal docs, it seems like inter folder copying might have different syntax than copying within the folder, whence the syntax error

**Comment by adiee5** [comment] 2024-02-23 15:48
Ok, it's a syntax error even on my install

**Comment by dacobi** [comment] 2024-02-23 15:50
The DOS command works fine and I wasn't coping between folders

**Comment by adiee5** [comment] 2024-02-23 15:51
yeah, the `cp` command simply doesn't work anymore and somehow nobody spotted it

**Comment by adiee5** [comment] 2024-02-23 16:40
> The DOS command works fine and I wasn't coping between folders

are you sure it works?

**Comment by dacobi** [comment] 2024-02-23 17:17
I have SHELL.PRG on my SD card as SH, which I copied to SHTEST with:

DOS"C:SHTEST=SH"

And ran with:
//SHTEST
RUN

And it works fine.

**Comment by adiee5** [comment] 2024-02-23 17:45
now we wait for @irmen to merge the pr

**Comment by irmen** [comment] 2024-02-23 22:20
fix is merged, thanks
it should work again now

**Comment by dacobi** [comment] 2024-02-24 10:10
I just pulled the change and compiled and it's working fine on pre-release R47

**Closed** 2024-02-24 10:52 UTC
