### ISSUE TITLE
rmdir doesn't work if you make a dir named aaaaaaaaaaaaaaa (15 a's), then try to remove it. You have to rmdir AAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by ToboterXP** [irmen/cx16shell#6] opened 2023-12-11 20:43 UTC

**Comment by irmen** [comment] 2023-12-12 20:00
cannot reproduce?

![image](https://github.com/irmen/cx16shell/assets/1771820/72c34910-b6ca-46e9-8d6b-c60a5c2b72ba)

**Comment by ToboterXP** [comment] 2023-12-18 21:19
I'm retrying it, it's not working anymore. Not sure what happened there. Maybe some additional variable played a role or something.

**Comment by irmen** [comment] 2023-12-18 21:24
Ok, closing this as can't reproduce

**Closed by irmen** 2023-12-18 21:24 UTC
